### ISSUE TITLE
Peer Review Feedback

### ISSUE THREAD

**Issue by haniicorn** [MWeygandt/ProjectWebsite#1]
Technical:
1. from the other pages, i can't click back into the home page from the nav bar, it just stays on whatever page i'm already on (but i can navigate to the other pages just not Home).
2. super minor issue but recipes is misspelled in the nav bar

Content:
1. would love to see pictures of the different cheeses in cheese types page! 
2. would be super interested in any super obscure fun facts that you input for the facts page, in addition to regular cheese facts

But regardless, the website looks really good, and i'm super interested in what the final page will look like!

**Comment by MWeygandt** [comment]
Thank you I fixed the spelling and added different pictures!
