### ISSUE TITLE
Diversify images of cheese in cheeses.html [Content]

### ISSUE THREAD

**Issue by OneDestinys** [MWeygandt/ProjectWebsite#2]
In cheeses.html, you use the same image of mozzarella for every type of cheese. Consider matching the image of cheese with the name of the cheese to improve reader clarity.
https://github.com/MWeygandt/ProjectWebsite/blob/e88ac229bdf3622c2d220615d633177b1729fe89/cheeses.html#L322-L345.

**Comment by MWeygandt** [comment]
Add different images :)
