### ISSUE TITLE
Homepage background cheese image repeating [Technical Issue]

### ISSUE THREAD

**Issue by OneDestinys** [MWeygandt/ProjectWebsite#4]
Your background image, homebackground.jpg, repeats when the site is on a large monitor. To fix this, add the following code to the CSS snippet below. Background-repeat being set to no-repeat will prevent your background-image from repeating over-and-over again. Background-size set to cover will make your image as large as possible, while maintaining the same aspect ratio, to fit your screen.
```
background-repeat: no-repeat;
background-size: cover;
```
https://github.com/MWeygandt/ProjectWebsite/blob/e88ac229bdf3622c2d220615d633177b1729fe89/index.html#L11-L14

**Comment by MWeygandt** [comment]
Thank you!
