### ISSUE TITLE
Inability to navigate back to homepage from other pages [Technical Issue]

### ISSUE THREAD

**Issue by OneDestinys** [MWeygandt/ProjectWebsite#5]
In all of your pages you have a line that is the 1st snippet. Change that line of code to the 2nd snippet in order to allow users to be able navigate back to homepage. You had #home as the href to go back to the homepage, without #home being defined.
https://github.com/MWeygandt/ProjectWebsite/blob/e88ac229bdf3622c2d220615d633177b1729fe89/cheeses.html#L103
`<li><a href="index.html">Home</a></li>`

**Comment by MWeygandt** [comment]
Fixed thank you!
