### ISSUE TITLE
Add a favicon [Content]

### ISSUE THREAD

**Issue by OneDestinys** [MWeygandt/ProjectWebsite#6]
Favicons can give your site a little more personality to them and can help users navigate to your site more easily when they have multiple tabs open. To add one, save an image you would like to be your favicon to your images folder under this repository. Then, on each of your pages, add:
`<link rel="icon" href="images/favicon.jpg">` 
Replace the "images/favicon.jpg" in href with your images relative path.  After following those steps, you should be good to go!

**Comment by MWeygandt** [comment]
added thanks!
